### ISSUE TITLE
What did you observe when training the Discriminator K times?

### ISSUE THREAD

**Issue by DanielTakeshi** [YunzhuLi/InfoGAIL#6]
Hi @YunzhuLi ,

Thanks for releasing the code.[ I observed here](https://github.com/YunzhuLi/InfoGAIL/blob/8b2544d865471c94ea3c3ab8abf09ae5875f2c1c/wgail_info_0/models.py#L352) that you usually train the discriminator 10 times for each generator update. Is it standard (at least in GAIL-like settings) to train the Discriminator more times than the Generator? The GAN tutorials seem to imply one gradient update for each of the players each iteration, but does the Discriminator need to be "strengthened" more here?  I am also wondering what other values you tested with (other than 10) and if you had comments on those.

Thank you.

**Comment by YunzhuLi** [comment]
Hi @DanielTakeshi ,

Here I'm using [Wasserstein GAN](https://arxiv.org/pdf/1701.07875.pdf) instead of vanilla GAN, which means that we can (and should) train the discriminator till optimality. I've tried several other values, and as long as the discriminator is trained adequately, we can achieve the desired results.

**Comment by DanielTakeshi** [comment]
Thanks!

**Comment by magnusja** [comment]
Hello @YunzhuLi,

thanks for sharing the code! I have a question regarding the justification for using a WGAN discriminator. In your paper, you mention that you would like to overcome the mode collapse as well as the vanishing gradient problem. As far as I am concerned for the mode collapse problem mostly the generator is affected, but in this case, the generator is trained using TRPO anyways. Am I missing something here? Regarding the vanishing gradients, these usually occur when training the generator using the gradients of the discriminator, which is also not the case here because there is no gradient feedback between policy network and discriminator. 
Thanks in advance!
